### PR TITLE
Fixed a bug where askForFilename($label) would not display the label

### PR DESCRIPTION
**Pull request by crnkovic**

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Thanks forgot to change that one

**Comment by crnkovic** [comment]
Whoops, I forgot to add docblock for `$label` param! If you don't mind do it in a second!

**Comment by patrickbrouwers** [comment]
Sure, I was about to update that myself :) But go ahead!

**Comment by crnkovic** [comment]
I'm thinking of passing a default value to the file name in the action modal as soon as I figure out how to pass a default value to Nova's Text field in an action field, lol.

I personally would love that, because when I click to run action, it would ask me for a filename but automatically fill a default input value with for example, `users-{datetime}`.

**Comment by patrickbrouwers** [comment]
Yes was thinking about the same thing as well, also still trying to figure that one out :) Would indeed be very useful!  Feel free to PR it, when you figure it out :)

**Pull request merged**
