### PR TITLE
Fixes an error where the download would fail to resolve #5

### LINKED ISSUE #5: Download failed - Server problem
When trying to download a file the browser would display `Failed - Server problem`.

## Log
```
Type error: Too few arguments to function Symfony\Component\HttpFoundation\BinaryFileResponse::deleteFileAfterSend(), 0 passed in vendor/maatwebsite/laravel-nova-excel/src/Http/Controllers/ExcelController.php on line 31 and exactly 1 expected
```

Running on Mac, Valet with Laravel 5.6.

### PR DESCRIPTION
**Pull request by m2de**

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Hm that's weird. I don't have this problem myself. Are you on a newer version of Symfony perhaps? (Laravel 5.7?)

**Comment by m2de** [comment]
Yeah I was surprised too. Laravel v5.6.15.

I looked up the source function and it indeed doesn't have a default value for the parameter in my install.

```
/**
     * If this is set to true, the file will be unlinked after the request is send
     * Note: If the X-Sendfile header is used, the deleteFileAfterSend setting will not be used.
     *
     * @param bool $shouldDelete
     *
     * @return $this
     */
    public function deleteFileAfterSend($shouldDelete)
    {
        $this->deleteFileAfterSend = $shouldDelete;

        return $this;
    }
```

**Comment by m2de** [comment]
```
"name": "symfony/http-foundation",
"version": "v4.0.7",
```

**Comment by patrickbrouwers** [comment]
Allright. Thanks for the fix!

**Pull request merged**
